package yin

// Headers is an export of the common headers from
// https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers
var Headers = struct {
	XRealIP                         string
	Connection                      string
	KeepAlive                       string
	ProxyAuthenticate               string
	ProxyAuthorization              string
	TE                              string
	Trailer                         string
	TransferEncoding                string
	Upgrade                         string
	WWWAuthenticate                 string
	Authorization                   string
	Age                             string
	CacheControl                    string
	ClearSiteData                   string
	Expires                         string
	Pragma                          string
	Warning                         string
	AcceptCH                        string
	AcceptCHLifetime                string
	EarlyData                       string
	ContentDPR                      string
	DPR                             string
	SaveData                        string
	ViewportWidth                   string
	Width                           string
	LastModified                    string
	ETag                            string
	IfModifiedSince                 string
	IfUnmodifiedSince               string
	IfMatch                         string
	IfNoneMatch                     string
	Vary                            string
	Accept                          string
	AcceptCharset                   string
	AcceptEncoding                  string
	AcceptLanguage                  string
	Expect                          string
	MaxForwards                     string
	Cookie                          string
	SetCookie                       string
	Cookie2                         string
	SetCookie2                      string
	AccessControlAllowOrigin        string
	AccessControlAllowCredentials   string
	AccessControlAllowHeaders       string
	AccessControlAllowMethods       string
	AccessControlExposeHeaders      string
	AccessControlMaxAge             string
	AccessControlRequestHeaders     string
	AccessControlRequestMethod      string
	Origin                          string
	TimingAllowOrigin               string
	XPermittedCrossDomainPolicies   string
	DNT                             string
	Tk                              string
	ContentDisposition              string
	ContentLength                   string
	ContentType                     string
	ContentEncoding                 string
	ContentLanguage                 string
	ContentLocation                 string
	Forwarded                       string
	XForwardedFor                   string
	XForwardedHost                  string
	XForwardedProto                 string
	Via                             string
	Location                        string
	From                            string
	Host                            string
	Referer                         string
	ReferrerPolicy                  string
	UserAgent                       string
	Allow                           string
	Server                          string
	AcceptRanges                    string
	Range                           string
	IfRange                         string
	ContentRange                    string
	CrossOriginResourcePolicy       string
	ContentSecurityPolicy           string
	ContentSecurityPolicyReportOnly string
	ExpectCT                        string
	FeaturePolicy                   string
	PublicKeyPins                   string
	PublicKeyPinsReportOnly         string
	StrictTransportSecurity         string
	UpgradeInsecureRequests         string
	upgradeinsecurerequests         string
	XContentTypeOptions             string
	XDownloadOptions                string
	XFrameOptions                   string
	XPoweredBy                      string
	XXSSProtection                  string
	LastEventID                     string
	NEL                             string
	PingFrom                        string
	PingTo                          string
	ReportTo                        string
	SecWebSocketKey                 string
	SecWebSocketExtensions          string
	SecWebSocketAccept              string
	SecWebSocketProtocol            string
	SecWebSocketVersion             string
	AcceptPushPolicy                string
	AcceptSignature                 string
	AltSvc                          string
	Date                            string
	LargeAllocation                 string
	Link                            string
	PushPolicy                      string
	RetryAfter                      string
	Signature                       string
	SignedHeaders                   string
	ServerTiming                    string
	SourceMap                       string
	XDNSPrefetchControl             string
	XFirefoxSpdy                    string
	XPingback                       string
	XRequestedWith                  string
	XRobotsTag                      string
	XUACompatible                   string
	Index                           string
	XHost                           string
	XOriginalScheme                 string
	XOriginalHost                   string
}{
	XHost:                           "X-Host",
	XOriginalScheme:                 "X-Original-Scheme",
	XOriginalHost:                   "X-Original-Host",
	XRealIP:                         "X-Real-IP",
	Connection:                      "Connection",
	KeepAlive:                       "Keep-Alive",
	ProxyAuthenticate:               "Proxy-Authenticate",
	ProxyAuthorization:              "Proxy-Authorization",
	TE:                              "TE",
	Trailer:                         "Trailer",
	TransferEncoding:                "Transfer-Encoding",
	Upgrade:                         "Upgrade",
	WWWAuthenticate:                 "WWW-Authenticate",
	Authorization:                   "Authorization",
	Age:                             "Age",
	CacheControl:                    "Cache-Control",
	ClearSiteData:                   "Clear-Site-Data",
	Expires:                         "Expires",
	Pragma:                          "Pragma",
	Warning:                         "Warning",
	AcceptCH:                        "Accept-CH",
	AcceptCHLifetime:                "Accept-CH-Lifetime",
	EarlyData:                       "Early-Data",
	ContentDPR:                      "Content-DPR",
	DPR:                             "DPR",
	SaveData:                        "Save-Data",
	ViewportWidth:                   "Viewport-Width",
	Width:                           "Width",
	LastModified:                    "Last-Modified",
	ETag:                            "ETag",
	IfModifiedSince:                 "If-Modified-Since",
	IfUnmodifiedSince:               "If-Unmodified-Since",
	IfMatch:                         "If-Match",
	IfNoneMatch:                     "If-None-Match",
	Vary:                            "Vary",
	Accept:                          "Accept",
	AcceptCharset:                   "Accept-Charset",
	AcceptEncoding:                  "Accept-Encoding",
	AcceptLanguage:                  "Accept-Language",
	Expect:                          "Expect",
	MaxForwards:                     "Max-Forwards",
	Cookie:                          "Cookie",
	SetCookie:                       "Set-Cookie",
	Cookie2:                         "Cookie2",
	SetCookie2:                      "Set-Cookie2",
	AccessControlAllowOrigin:        "Access-Control-Allow-Origin",
	AccessControlAllowCredentials:   "Access-Control-Allow-Credentials",
	AccessControlAllowHeaders:       "Access-Control-Allow-Headers",
	AccessControlAllowMethods:       "Access-Control-Allow-Methods",
	AccessControlExposeHeaders:      "Access-Control-Expose-Headers",
	AccessControlMaxAge:             "Access-Control-Max-Age",
	AccessControlRequestHeaders:     "Access-Control-Request-Headers",
	AccessControlRequestMethod:      "Access-Control-Request-Method",
	Origin:                          "Origin",
	TimingAllowOrigin:               "Timing-Allow-Origin",
	XPermittedCrossDomainPolicies:   "X-Permitted-Cross-Domain-Policies",
	DNT:                             "DNT",
	Tk:                              "Tk",
	ContentDisposition:              "Content-Disposition",
	ContentLength:                   "Content-Length",
	ContentType:                     "Content-Type",
	ContentEncoding:                 "Content-Encoding",
	ContentLanguage:                 "Content-Language",
	ContentLocation:                 "Content-Location",
	Forwarded:                       "Forwarded",
	XForwardedFor:                   "X-Forwarded-For",
	XForwardedHost:                  "X-Forwarded-Host",
	XForwardedProto:                 "X-Forwarded-Proto",
	Via:                             "Via",
	Location:                        "Location",
	From:                            "From",
	Host:                            "Host",
	Referer:                         "Referer",
	ReferrerPolicy:                  "Referrer-Policy",
	UserAgent:                       "User-Agent",
	Allow:                           "Allow",
	Server:                          "Server",
	AcceptRanges:                    "Accept-Ranges",
	Range:                           "Range",
	IfRange:                         "If-Range",
	ContentRange:                    "Content-Range",
	CrossOriginResourcePolicy:       "Cross-Origin-Resource-Policy",
	ContentSecurityPolicy:           "Content-Security-Policy",
	ContentSecurityPolicyReportOnly: "Content-Security-Policy-Report-Only",
	ExpectCT:                        "Expect-CT",
	FeaturePolicy:                   "Feature-Policy",
	PublicKeyPins:                   "Public-Key-Pins",
	PublicKeyPinsReportOnly:         "Public-Key-Pins-Report-Only",
	StrictTransportSecurity:         "Strict-Transport-Security",
	UpgradeInsecureRequests:         "Upgrade-Insecure-Requests",
	upgradeinsecurerequests:         "upgrade-insecure-requests",
	XContentTypeOptions:             "X-Content-Type-Options",
	XDownloadOptions:                "X-Download-Options",
	XFrameOptions:                   "X-Frame-Options",
	XPoweredBy:                      "X-Powered-By",
	XXSSProtection:                  "X-XSS-Protection",
	LastEventID:                     "Last-Event-ID",
	NEL:                             "NEL",
	PingFrom:                        "Ping-From",
	PingTo:                          "Ping-To",
	ReportTo:                        "Report-To",
	SecWebSocketKey:                 "Sec-WebSocket-Key",
	SecWebSocketExtensions:          "Sec-WebSocket-Extensions",
	SecWebSocketAccept:              "Sec-WebSocket-Accept",
	SecWebSocketProtocol:            "Sec-WebSocket-Protocol",
	SecWebSocketVersion:             "Sec-WebSocket-Version",
	AcceptPushPolicy:                "Accept-Push-Policy",
	AcceptSignature:                 "Accept-Signature",
	AltSvc:                          "Alt-Svc",
	Date:                            "Date",
	LargeAllocation:                 "Large-Allocation",
	Link:                            "Link",
	PushPolicy:                      "Push-Policy",
	RetryAfter:                      "Retry-After",
	Signature:                       "Signature",
	SignedHeaders:                   "Signed-Headers",
	ServerTiming:                    "Server-Timing",
	SourceMap:                       "SourceMap",
	XDNSPrefetchControl:             "X-DNS-Prefetch-Control",
	XFirefoxSpdy:                    "X-Firefox-Spdy",
	XPingback:                       "X-Pingback",
	XRequestedWith:                  "X-Requested-With",
	XRobotsTag:                      "X-Robots-Tag",
	XUACompatible:                   "X-UA-Compatible",
	Index:                           "Index",
}
